{
    "deleted": null,
    "id": 80815345,
    "matching_downtimes": [],
    "message": "There are more than **2 commits in a row failing** on {{[@git.branch].name}} for pipeline {{[@ci.pipeline.name].name}}.\n\n_What to do next:_\n\n1. Navigate to the [BuildKite - main builds](https://buildkite.com/handshake/handshake/builds?branch=main)\n2. Inspect the recent failures and see if they are related.\n3. Is there a flaky test? [Review Handling Flakey Specs and take the appropriate action](https://joinhandshake.atlassian.net/wiki/spaces/DA/pages/755138564/Handling+Flakey+Specs)\n4. Did a recent PR cause the failures? Reach out to the author and ask them for support.\n\n@slack-incidents-dev-experience",
    "multi": true,
    "name": "Multiple Failures Detected on Main",
    "options": {
        "enable_logs_sample": true,
        "groupby_simple_monitor": false,
        "include_tags": true,
        "new_host_delay": 300,
        "notify_audit": false,
        "on_missing_data": "default",
        "restriction_query": null,
        "silenced": {},
        "thresholds": {
            "critical": 2.0
        }
    },
    "query": "ci-pipelines(\"ci_level:pipeline @git.branch:main @ci.status:error @ci.pipeline.name:handshake\").rollup(\"count\").by(\"@ci.pipeline.name,@git.branch\").last(\"30m\") > 2",
    "tags": [
        "team:devx",
        "env:internal"
    ],
    "type": "ci-pipelines alert"
}